[project]
name = "exteragram-plugin-template"
version = "0.1.0"
description = "extera/Ayu-Gram template plugin"
license = "MIT"
license-files = ["LICENSE"]
requires-python = ">=3.14"
dependencies = [
    "exteragram-utils>=0.1.3",
]

[dependency-groups]
dev = [
    "ruff>=0.15.4",
    "ty>=0.0.15",
]

[tool.ty.environment]
extra-paths = ["stubs"]
