[versions]
aliuhook = "1.1.3"
desugar_jdk_libs = "2.1.5"
#noinspection GradleDependency
kotlin = "2.2.0"
kotlinxCoroutinesCore = "1.10.2"
kotlinxCollectionsImmutable = "0.4.0"
i18n4k = "0.11.2"
recyclerview = "1.4.0"
lifecycle = "2.6.2"

[libraries]
aliuhook = { module = "com.aliucord:Aliuhook", version.ref = "aliuhook" }
desugar_jdk_libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar_jdk_libs" }
jetbrains-kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesCore" }
kotlinx-collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinxCollectionsImmutable" }
i18n4k-core = { module = "de.comahe.i18n4k:i18n4k-core", version.ref = "i18n4k" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
androidx-lifecycle-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel", version.ref = "lifecycle" }
