#!/usr/bin/env python3
"""Embed a classes.dex into the plugin .py as a base64 comment block.

The DEX is LZMA-compressed and base64-encoded, then written between the marker
comments (see JvmPluginBridge in the plugin). Storing the payload as a comment
(not a string literal) keeps its bytes out of the interpreter heap: comments are
dropped by the tokenizer and never become a live Python object.

Usage: embed_dex.py <path/to/classes.dex> <path/to/source.py> [path/to/output.py]

Without an output path the source is rewritten in place. The reusable
``embed_source`` helper is what the dev watcher uses to build the temp file it
hands to extera.
"""

# generated by claude

import base64
import lzma
import sys

BEGIN = "# === EMDEDDED DEX BEGIN ==="
END = "# === EMDEDDED DEX END ==="
# base64 chars per line (kept modest so the source stays diff-friendly)
LINE_WIDTH = 120
LZMA_PRESET = 9 | lzma.PRESET_EXTREME


def compress(data: bytes) -> bytes:
    return lzma.compress(data, format=lzma.FORMAT_XZ, preset=LZMA_PRESET)


def embed_source(source: str, dex: bytes) -> str:
    """Return ``source`` with ``dex`` packed between the marker comments."""
    lines = source.splitlines()

    try:
        begin_idx = next(i for i, line in enumerate(lines) if line.strip() == BEGIN)
        end_idx = next(i for i, line in enumerate(lines) if line.strip() == END)
    except StopIteration:
        raise ValueError("DEX markers not found in source") from None

    if end_idx <= begin_idx:
        raise ValueError("END marker precedes BEGIN marker")

    encoded = base64.b64encode(compress(dex)).decode("ascii")
    payload = [
        f"# {encoded[i : i + LINE_WIDTH]}" for i in range(0, len(encoded), LINE_WIDTH)
    ]

    new_lines = lines[: begin_idx + 1] + payload + lines[end_idx:]
    return "\n".join(new_lines) + "\n"


def main() -> int:
    if len(sys.argv) not in (3, 4):
        print(
            f"usage: {sys.argv[0]} <classes.dex> <source.py> [output.py]",
            file=sys.stderr,
        )
        return 2

    dex_path, source_path = sys.argv[1], sys.argv[2]
    output_path = sys.argv[3] if len(sys.argv) == 4 else source_path

    with open(dex_path, "rb") as f:
        dex = f.read()

    with open(source_path, "r", encoding="utf-8") as f:
        source = f.read()

    try:
        embedded = embed_source(source, dex)
    except ValueError as e:
        print(f"error: {e} ({source_path})", file=sys.stderr)
        return 1

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(embedded)

    print(f"embedded {len(dex)} bytes of DEX into {output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
